module WB
  class ConfigTemplate
    def self.content
      CONTENT
    end

    CONTENT = <<~WORKBOOKRC
      # Auto generated by wb #{WB::VERSION}
      workbook:
        working_hours: "9-17"
        personal: "~/Dropbox/workbooks/personal.md"
        work: "~/Dropbox/workbooks/work.md"
        project:
          note_folder: ".note"
    WORKBOOKRC
    private_constant :CONTENT
  end
end
